title: Nathan Dodd
logo: assets/Headshot.jpg
description: Self-driven engineer with history of leadership, meeting goals, and excelling in team environments
#show_downloads: true
theme: jekyll-theme-minimal
